#ifndef __PID_DATA_BUILDER_HPP__
#define __PID_DATA_BUILDER_HPP__

#include <arrow/api.h>
#include "PaassRootStruct.hpp"

class PIDDataBuilder
{
public:
    PIDDataBuilder()
    {
        cross_scint_b1_energy = std::make_shared<arrow::DoubleBuilder>();
        cross_scint_b1_time = std::make_shared<arrow::DoubleBuilder>();
        cross_scint_t1_energy = std::make_shared<arrow::DoubleBuilder>();
        cross_scint_t1_time = std::make_shared<arrow::DoubleBuilder>();
        cross_scint_v1_energy = std::make_shared<arrow::DoubleBuilder>();
        cross_scint_v1_time = std::make_shared<arrow::DoubleBuilder>();
        cross_scint_v1_qdc = std::make_shared<arrow::DoubleBuilder>();
        cross_scint_v2_energy = std::make_shared<arrow::DoubleBuilder>();
        cross_scint_v2_time = std::make_shared<arrow::DoubleBuilder>();
        cross_scint_v2_qdc = std::make_shared<arrow::DoubleBuilder>();
        cross_scint_v3_energy = std::make_shared<arrow::DoubleBuilder>();
        cross_scint_v3_time = std::make_shared<arrow::DoubleBuilder>();
        cross_scint_v3_qdc = std::make_shared<arrow::DoubleBuilder>();
        cross_scint_v4_energy = std::make_shared<arrow::DoubleBuilder>();
        cross_scint_v4_time = std::make_shared<arrow::DoubleBuilder>();
        cross_scint_v4_qdc = std::make_shared<arrow::DoubleBuilder>();
        cross_pin_0_energy = std::make_shared<arrow::DoubleBuilder>();
        cross_pin_0_tracemax = std::make_shared<arrow::DoubleBuilder>();
        cross_pin_0_traceqdc = std::make_shared<arrow::DoubleBuilder>();
        cross_pin_0_time = std::make_shared<arrow::DoubleBuilder>();
        cross_pin_1_energy = std::make_shared<arrow::DoubleBuilder>();
        cross_pin_1_tracemax = std::make_shared<arrow::DoubleBuilder>();
        cross_pin_1_traceqdc = std::make_shared<arrow::DoubleBuilder>();
        cross_pin_1_time = std::make_shared<arrow::DoubleBuilder>();
        cross_pin_2_energy = std::make_shared<arrow::DoubleBuilder>();
        cross_pin_2_tracemax = std::make_shared<arrow::DoubleBuilder>();
        cross_pin_2_traceqdc = std::make_shared<arrow::DoubleBuilder>();
        cross_pin_2_time = std::make_shared<arrow::DoubleBuilder>();
        cross_pin_3_energy = std::make_shared<arrow::DoubleBuilder>();
        cross_pin_3_tracemax = std::make_shared<arrow::DoubleBuilder>();
        cross_pin_3_traceqdc = std::make_shared<arrow::DoubleBuilder>();
        cross_pin_3_time = std::make_shared<arrow::DoubleBuilder>();
        db3_scint_L = std::make_shared<arrow::DoubleBuilder>();
        db3_scint_R = std::make_shared<arrow::DoubleBuilder>();
        db3_ppac_upstream = std::make_shared<arrow::DoubleBuilder>();
        db3_ppac_upstream_left = std::make_shared<arrow::DoubleBuilder>();
        db3_ppac_upstream_right = std::make_shared<arrow::DoubleBuilder>();
        db3_ppac_upstream_up = std::make_shared<arrow::DoubleBuilder>();
        db3_ppac_upstream_down = std::make_shared<arrow::DoubleBuilder>();
        db3_ppac_upstream_LR = std::make_shared<arrow::DoubleBuilder>();
        db3_ppac_upstream_UD = std::make_shared<arrow::DoubleBuilder>();
        db3_ppac_downstream = std::make_shared<arrow::DoubleBuilder>();
        db3_ppac_downstream_left = std::make_shared<arrow::DoubleBuilder>();
        db3_ppac_downstream_right = std::make_shared<arrow::DoubleBuilder>();
        db3_ppac_downstream_up = std::make_shared<arrow::DoubleBuilder>();
        db3_ppac_downstream_down = std::make_shared<arrow::DoubleBuilder>();
        db3_ppac_downstream_LR = std::make_shared<arrow::DoubleBuilder>();
        db3_ppac_downstream_UD = std::make_shared<arrow::DoubleBuilder>();
        db4_ppac_left = std::make_shared<arrow::DoubleBuilder>();
        db4_ppac_right = std::make_shared<arrow::DoubleBuilder>();
        db4_ppac_up = std::make_shared<arrow::DoubleBuilder>();
        db4_ppac_down = std::make_shared<arrow::DoubleBuilder>();
        db4_ppac_LR = std::make_shared<arrow::DoubleBuilder>();
        db4_ppac_UD = std::make_shared<arrow::DoubleBuilder>();
        db5_ppac_upstream = std::make_shared<arrow::DoubleBuilder>();
        db5_ppac_upstream_left = std::make_shared<arrow::DoubleBuilder>();
        db5_ppac_upstream_right = std::make_shared<arrow::DoubleBuilder>();
        db5_ppac_upstream_up = std::make_shared<arrow::DoubleBuilder>();
        db5_ppac_upstream_down = std::make_shared<arrow::DoubleBuilder>();
        db5_ppac_upstream_LR = std::make_shared<arrow::DoubleBuilder>();
        db5_ppac_upstream_UD = std::make_shared<arrow::DoubleBuilder>();
        db5_ppac_downstream = std::make_shared<arrow::DoubleBuilder>();
        db5_ppac_downstream_left = std::make_shared<arrow::DoubleBuilder>();
        db5_ppac_downstream_right = std::make_shared<arrow::DoubleBuilder>();
        db5_ppac_downstream_up = std::make_shared<arrow::DoubleBuilder>();
        db5_ppac_downstream_down = std::make_shared<arrow::DoubleBuilder>();
        db5_ppac_downstream_LR = std::make_shared<arrow::DoubleBuilder>();
        db5_ppac_downstream_UD = std::make_shared<arrow::DoubleBuilder>();
        tof0 = std::make_shared<arrow::DoubleBuilder>();
        tof1 = std::make_shared<arrow::DoubleBuilder>();
        tof2 = std::make_shared<arrow::DoubleBuilder>();
        tof3 = std::make_shared<arrow::DoubleBuilder>();
        tof4 = std::make_shared<arrow::DoubleBuilder>();
        tof5 = std::make_shared<arrow::DoubleBuilder>();
        fit_energy = std::make_shared<arrow::DoubleBuilder>();
        yso_energy = std::make_shared<arrow::DoubleBuilder>();
        rit_energy = std::make_shared<arrow::DoubleBuilder>();
    }

    virtual ~PIDDataBuilder() {}

    int FillArrow(const std::vector<processor_struct::PID> &input)
    {
        if (!input.empty())
        {
            PARQUET_THROW_NOT_OK(cross_scint_b1_energy->Append(input.at(0).cross_scint_b1_energy));
            PARQUET_THROW_NOT_OK(cross_scint_b1_time->Append(input.at(0).cross_scint_b1_time));
            PARQUET_THROW_NOT_OK(cross_scint_t1_energy->Append(input.at(0).cross_scint_t1_energy));
            PARQUET_THROW_NOT_OK(cross_scint_t1_time->Append(input.at(0).cross_scint_t1_time));
            PARQUET_THROW_NOT_OK(cross_scint_v1_energy->Append(input.at(0).cross_scint_v1_energy));
            PARQUET_THROW_NOT_OK(cross_scint_v1_time->Append(input.at(0).cross_scint_v1_time));
            PARQUET_THROW_NOT_OK(cross_scint_v1_qdc->Append(input.at(0).cross_scint_v1_qdc));
            PARQUET_THROW_NOT_OK(cross_scint_v2_energy->Append(input.at(0).cross_scint_v2_energy));
            PARQUET_THROW_NOT_OK(cross_scint_v2_time->Append(input.at(0).cross_scint_v2_time));
            PARQUET_THROW_NOT_OK(cross_scint_v2_qdc->Append(input.at(0).cross_scint_v2_qdc));
            PARQUET_THROW_NOT_OK(cross_scint_v3_energy->Append(input.at(0).cross_scint_v3_energy));
            PARQUET_THROW_NOT_OK(cross_scint_v3_time->Append(input.at(0).cross_scint_v3_time));
            PARQUET_THROW_NOT_OK(cross_scint_v3_qdc->Append(input.at(0).cross_scint_v3_qdc));
            PARQUET_THROW_NOT_OK(cross_scint_v4_energy->Append(input.at(0).cross_scint_v4_energy));
            PARQUET_THROW_NOT_OK(cross_scint_v4_time->Append(input.at(0).cross_scint_v4_time));
            PARQUET_THROW_NOT_OK(cross_scint_v4_qdc->Append(input.at(0).cross_scint_v4_qdc));
            PARQUET_THROW_NOT_OK(cross_pin_0_energy->Append(input.at(0).cross_pin_0_energy));
            PARQUET_THROW_NOT_OK(cross_pin_0_tracemax->Append(input.at(0).cross_pin_0_tracemax));
            PARQUET_THROW_NOT_OK(cross_pin_0_traceqdc->Append(input.at(0).cross_pin_0_traceqdc));
            PARQUET_THROW_NOT_OK(cross_pin_0_time->Append(input.at(0).cross_pin_0_time));
            PARQUET_THROW_NOT_OK(cross_pin_1_energy->Append(input.at(0).cross_pin_1_energy));
            PARQUET_THROW_NOT_OK(cross_pin_1_tracemax->Append(input.at(0).cross_pin_1_tracemax));
            PARQUET_THROW_NOT_OK(cross_pin_1_traceqdc->Append(input.at(0).cross_pin_1_traceqdc));
            PARQUET_THROW_NOT_OK(cross_pin_1_time->Append(input.at(0).cross_pin_1_time));
            PARQUET_THROW_NOT_OK(cross_pin_2_energy->Append(input.at(0).cross_pin_2_energy));
            PARQUET_THROW_NOT_OK(cross_pin_2_tracemax->Append(input.at(0).cross_pin_2_tracemax));
            PARQUET_THROW_NOT_OK(cross_pin_2_traceqdc->Append(input.at(0).cross_pin_2_traceqdc));
            PARQUET_THROW_NOT_OK(cross_pin_2_time->Append(input.at(0).cross_pin_2_time));
            PARQUET_THROW_NOT_OK(cross_pin_3_energy->Append(input.at(0).cross_pin_3_energy));
            PARQUET_THROW_NOT_OK(cross_pin_3_tracemax->Append(input.at(0).cross_pin_3_tracemax));
            PARQUET_THROW_NOT_OK(cross_pin_3_traceqdc->Append(input.at(0).cross_pin_3_traceqdc));
            PARQUET_THROW_NOT_OK(cross_pin_3_time->Append(input.at(0).cross_pin_3_time));
            PARQUET_THROW_NOT_OK(db3_scint_L->Append(input.at(0).db3_scint_L));
            PARQUET_THROW_NOT_OK(db3_scint_R->Append(input.at(0).db3_scint_R));
            PARQUET_THROW_NOT_OK(db3_ppac_upstream->Append(input.at(0).db3_ppac_upstream));
            PARQUET_THROW_NOT_OK(db3_ppac_upstream_left->Append(input.at(0).db3_ppac_upstream_left));
            PARQUET_THROW_NOT_OK(db3_ppac_upstream_right->Append(input.at(0).db3_ppac_upstream_right));
            PARQUET_THROW_NOT_OK(db3_ppac_upstream_up->Append(input.at(0).db3_ppac_upstream_up));
            PARQUET_THROW_NOT_OK(db3_ppac_upstream_down->Append(input.at(0).db3_ppac_upstream_down));
            PARQUET_THROW_NOT_OK(db3_ppac_upstream_LR->Append(input.at(0).db3_ppac_upstream_LR));
            PARQUET_THROW_NOT_OK(db3_ppac_upstream_UD->Append(input.at(0).db3_ppac_upstream_UD));
            PARQUET_THROW_NOT_OK(db3_ppac_downstream->Append(input.at(0).db3_ppac_downstream));
            PARQUET_THROW_NOT_OK(db3_ppac_downstream_left->Append(input.at(0).db3_ppac_downstream_left));
            PARQUET_THROW_NOT_OK(db3_ppac_downstream_right->Append(input.at(0).db3_ppac_downstream_right));
            PARQUET_THROW_NOT_OK(db3_ppac_downstream_up->Append(input.at(0).db3_ppac_downstream_up));
            PARQUET_THROW_NOT_OK(db3_ppac_downstream_down->Append(input.at(0).db3_ppac_downstream_down));
            PARQUET_THROW_NOT_OK(db3_ppac_downstream_LR->Append(input.at(0).db3_ppac_downstream_LR));
            PARQUET_THROW_NOT_OK(db3_ppac_downstream_UD->Append(input.at(0).db3_ppac_downstream_UD));
            PARQUET_THROW_NOT_OK(db4_ppac_left->Append(input.at(0).db4_ppac_left));
            PARQUET_THROW_NOT_OK(db4_ppac_right->Append(input.at(0).db4_ppac_right));
            PARQUET_THROW_NOT_OK(db4_ppac_up->Append(input.at(0).db4_ppac_up));
            PARQUET_THROW_NOT_OK(db4_ppac_down->Append(input.at(0).db4_ppac_down));
            PARQUET_THROW_NOT_OK(db4_ppac_LR->Append(input.at(0).db4_ppac_LR));
            PARQUET_THROW_NOT_OK(db4_ppac_UD->Append(input.at(0).db4_ppac_UD));
            PARQUET_THROW_NOT_OK(db5_ppac_upstream->Append(input.at(0).db5_ppac_upstream));
            PARQUET_THROW_NOT_OK(db5_ppac_upstream_left->Append(input.at(0).db5_ppac_upstream_left));
            PARQUET_THROW_NOT_OK(db5_ppac_upstream_right->Append(input.at(0).db5_ppac_upstream_right));
            PARQUET_THROW_NOT_OK(db5_ppac_upstream_up->Append(input.at(0).db5_ppac_upstream_up));
            PARQUET_THROW_NOT_OK(db5_ppac_upstream_down->Append(input.at(0).db5_ppac_upstream_down));
            PARQUET_THROW_NOT_OK(db5_ppac_upstream_LR->Append(input.at(0).db5_ppac_upstream_LR));
            PARQUET_THROW_NOT_OK(db5_ppac_upstream_UD->Append(input.at(0).db5_ppac_upstream_UD));
            PARQUET_THROW_NOT_OK(db5_ppac_downstream->Append(input.at(0).db5_ppac_downstream));
            PARQUET_THROW_NOT_OK(db5_ppac_downstream_left->Append(input.at(0).db5_ppac_downstream_left));
            PARQUET_THROW_NOT_OK(db5_ppac_downstream_right->Append(input.at(0).db5_ppac_downstream_right));
            PARQUET_THROW_NOT_OK(db5_ppac_downstream_up->Append(input.at(0).db5_ppac_downstream_up));
            PARQUET_THROW_NOT_OK(db5_ppac_downstream_down->Append(input.at(0).db5_ppac_downstream_down));
            PARQUET_THROW_NOT_OK(db5_ppac_downstream_LR->Append(input.at(0).db5_ppac_downstream_LR));
            PARQUET_THROW_NOT_OK(db5_ppac_downstream_UD->Append(input.at(0).db5_ppac_downstream_UD));
            PARQUET_THROW_NOT_OK(tof0->Append(input.at(0).tof0));
            PARQUET_THROW_NOT_OK(tof1->Append(input.at(0).tof1));
            PARQUET_THROW_NOT_OK(tof2->Append(input.at(0).tof2));
            PARQUET_THROW_NOT_OK(tof3->Append(input.at(0).tof3));
            PARQUET_THROW_NOT_OK(tof4->Append(input.at(0).tof4));
            PARQUET_THROW_NOT_OK(tof5->Append(input.at(0).tof5));
            PARQUET_THROW_NOT_OK(fit_energy->Append(input.at(0).fit_energy));
            PARQUET_THROW_NOT_OK(yso_energy->Append(input.at(0).yso_energy));
            PARQUET_THROW_NOT_OK(rit_energy->Append(input.at(0).rit_energy));

            return 1;
        }
        return 0;
    }

    void Finalize(arrow::FieldVector &fvec, arrow::ArrayVector &avec)
    {
        std::shared_ptr<arrow::Array> cross_scint_b1_energyArray;
        std::shared_ptr<arrow::Array> cross_scint_b1_timeArray;
        std::shared_ptr<arrow::Array> cross_scint_t1_energyArray;
        std::shared_ptr<arrow::Array> cross_scint_t1_timeArray;
        std::shared_ptr<arrow::Array> cross_scint_v1_energyArray;
        std::shared_ptr<arrow::Array> cross_scint_v1_timeArray;
        std::shared_ptr<arrow::Array> cross_scint_v1_qdcArray;
        std::shared_ptr<arrow::Array> cross_scint_v2_energyArray;
        std::shared_ptr<arrow::Array> cross_scint_v2_timeArray;
        std::shared_ptr<arrow::Array> cross_scint_v2_qdcArray;
        std::shared_ptr<arrow::Array> cross_scint_v3_energyArray;
        std::shared_ptr<arrow::Array> cross_scint_v3_timeArray;
        std::shared_ptr<arrow::Array> cross_scint_v3_qdcArray;
        std::shared_ptr<arrow::Array> cross_scint_v4_energyArray;
        std::shared_ptr<arrow::Array> cross_scint_v4_timeArray;
        std::shared_ptr<arrow::Array> cross_scint_v4_qdcArray;
        std::shared_ptr<arrow::Array> cross_pin_0_energyArray;
        std::shared_ptr<arrow::Array> cross_pin_0_tracemaxArray;
        std::shared_ptr<arrow::Array> cross_pin_0_traceqdcArray;
        std::shared_ptr<arrow::Array> cross_pin_0_timeArray;
        std::shared_ptr<arrow::Array> cross_pin_1_energyArray;
        std::shared_ptr<arrow::Array> cross_pin_1_tracemaxArray;
        std::shared_ptr<arrow::Array> cross_pin_1_traceqdcArray;
        std::shared_ptr<arrow::Array> cross_pin_1_timeArray;
        std::shared_ptr<arrow::Array> cross_pin_2_energyArray;
        std::shared_ptr<arrow::Array> cross_pin_2_tracemaxArray;
        std::shared_ptr<arrow::Array> cross_pin_2_traceqdcArray;
        std::shared_ptr<arrow::Array> cross_pin_2_timeArray;
        std::shared_ptr<arrow::Array> cross_pin_3_energyArray;
        std::shared_ptr<arrow::Array> cross_pin_3_tracemaxArray;
        std::shared_ptr<arrow::Array> cross_pin_3_traceqdcArray;
        std::shared_ptr<arrow::Array> cross_pin_3_timeArray;
        std::shared_ptr<arrow::Array> db3_scint_LArray;
        std::shared_ptr<arrow::Array> db3_scint_RArray;
        std::shared_ptr<arrow::Array> db3_ppac_upstreamArray;
        std::shared_ptr<arrow::Array> db3_ppac_upstream_leftArray;
        std::shared_ptr<arrow::Array> db3_ppac_upstream_rightArray;
        std::shared_ptr<arrow::Array> db3_ppac_upstream_upArray;
        std::shared_ptr<arrow::Array> db3_ppac_upstream_downArray;
        std::shared_ptr<arrow::Array> db3_ppac_upstream_LRArray;
        std::shared_ptr<arrow::Array> db3_ppac_upstream_UDArray;
        std::shared_ptr<arrow::Array> db3_ppac_downstreamArray;
        std::shared_ptr<arrow::Array> db3_ppac_downstream_leftArray;
        std::shared_ptr<arrow::Array> db3_ppac_downstream_rightArray;
        std::shared_ptr<arrow::Array> db3_ppac_downstream_upArray;
        std::shared_ptr<arrow::Array> db3_ppac_downstream_downArray;
        std::shared_ptr<arrow::Array> db3_ppac_downstream_LRArray;
        std::shared_ptr<arrow::Array> db3_ppac_downstream_UDArray;
        std::shared_ptr<arrow::Array> db4_ppac_leftArray;
        std::shared_ptr<arrow::Array> db4_ppac_rightArray;
        std::shared_ptr<arrow::Array> db4_ppac_upArray;
        std::shared_ptr<arrow::Array> db4_ppac_downArray;
        std::shared_ptr<arrow::Array> db4_ppac_LRArray;
        std::shared_ptr<arrow::Array> db4_ppac_UDArray;
        std::shared_ptr<arrow::Array> db5_ppac_upstreamArray;
        std::shared_ptr<arrow::Array> db5_ppac_upstream_leftArray;
        std::shared_ptr<arrow::Array> db5_ppac_upstream_rightArray;
        std::shared_ptr<arrow::Array> db5_ppac_upstream_upArray;
        std::shared_ptr<arrow::Array> db5_ppac_upstream_downArray;
        std::shared_ptr<arrow::Array> db5_ppac_upstream_LRArray;
        std::shared_ptr<arrow::Array> db5_ppac_upstream_UDArray;
        std::shared_ptr<arrow::Array> db5_ppac_downstreamArray;
        std::shared_ptr<arrow::Array> db5_ppac_downstream_leftArray;
        std::shared_ptr<arrow::Array> db5_ppac_downstream_rightArray;
        std::shared_ptr<arrow::Array> db5_ppac_downstream_upArray;
        std::shared_ptr<arrow::Array> db5_ppac_downstream_downArray;
        std::shared_ptr<arrow::Array> db5_ppac_downstream_LRArray;
        std::shared_ptr<arrow::Array> db5_ppac_downstream_UDArray;
        std::shared_ptr<arrow::Array> tof0Array;
        std::shared_ptr<arrow::Array> tof1Array;
        std::shared_ptr<arrow::Array> tof2Array;
        std::shared_ptr<arrow::Array> tof3Array;
        std::shared_ptr<arrow::Array> tof4Array;
        std::shared_ptr<arrow::Array> tof5Array;
        std::shared_ptr<arrow::Array> fit_energyArray;
        std::shared_ptr<arrow::Array> yso_energyArray;
        std::shared_ptr<arrow::Array> rit_energyArray;

        PARQUET_THROW_NOT_OK(cross_scint_b1_energy->Finish(&cross_scint_b1_energyArray));
        PARQUET_THROW_NOT_OK(cross_scint_b1_time->Finish(&cross_scint_b1_timeArray));
        PARQUET_THROW_NOT_OK(cross_scint_t1_energy->Finish(&cross_scint_t1_energyArray));
        PARQUET_THROW_NOT_OK(cross_scint_t1_time->Finish(&cross_scint_t1_timeArray));
        PARQUET_THROW_NOT_OK(cross_scint_v1_energy->Finish(&cross_scint_v1_energyArray));
        PARQUET_THROW_NOT_OK(cross_scint_v1_time->Finish(&cross_scint_v1_timeArray));
        PARQUET_THROW_NOT_OK(cross_scint_v1_qdc->Finish(&cross_scint_v1_qdcArray));
        PARQUET_THROW_NOT_OK(cross_scint_v2_energy->Finish(&cross_scint_v2_energyArray));
        PARQUET_THROW_NOT_OK(cross_scint_v2_time->Finish(&cross_scint_v2_timeArray));
        PARQUET_THROW_NOT_OK(cross_scint_v2_qdc->Finish(&cross_scint_v2_qdcArray));
        PARQUET_THROW_NOT_OK(cross_scint_v3_energy->Finish(&cross_scint_v3_energyArray));
        PARQUET_THROW_NOT_OK(cross_scint_v3_time->Finish(&cross_scint_v3_timeArray));
        PARQUET_THROW_NOT_OK(cross_scint_v3_qdc->Finish(&cross_scint_v3_qdcArray));
        PARQUET_THROW_NOT_OK(cross_scint_v4_energy->Finish(&cross_scint_v4_energyArray));
        PARQUET_THROW_NOT_OK(cross_scint_v4_time->Finish(&cross_scint_v4_timeArray));
        PARQUET_THROW_NOT_OK(cross_scint_v4_qdc->Finish(&cross_scint_v4_qdcArray));
        PARQUET_THROW_NOT_OK(cross_pin_0_energy->Finish(&cross_pin_0_energyArray));
        PARQUET_THROW_NOT_OK(cross_pin_0_tracemax->Finish(&cross_pin_0_tracemaxArray));
        PARQUET_THROW_NOT_OK(cross_pin_0_traceqdc->Finish(&cross_pin_0_traceqdcArray));
        PARQUET_THROW_NOT_OK(cross_pin_0_time->Finish(&cross_pin_0_timeArray));
        PARQUET_THROW_NOT_OK(cross_pin_1_energy->Finish(&cross_pin_1_energyArray));
        PARQUET_THROW_NOT_OK(cross_pin_1_tracemax->Finish(&cross_pin_1_tracemaxArray));
        PARQUET_THROW_NOT_OK(cross_pin_1_traceqdc->Finish(&cross_pin_1_traceqdcArray));
        PARQUET_THROW_NOT_OK(cross_pin_1_time->Finish(&cross_pin_1_timeArray));
        PARQUET_THROW_NOT_OK(cross_pin_2_energy->Finish(&cross_pin_2_energyArray));
        PARQUET_THROW_NOT_OK(cross_pin_2_tracemax->Finish(&cross_pin_2_tracemaxArray));
        PARQUET_THROW_NOT_OK(cross_pin_2_traceqdc->Finish(&cross_pin_2_traceqdcArray));
        PARQUET_THROW_NOT_OK(cross_pin_2_time->Finish(&cross_pin_2_timeArray));
        PARQUET_THROW_NOT_OK(cross_pin_3_energy->Finish(&cross_pin_3_energyArray));
        PARQUET_THROW_NOT_OK(cross_pin_3_tracemax->Finish(&cross_pin_3_tracemaxArray));
        PARQUET_THROW_NOT_OK(cross_pin_3_traceqdc->Finish(&cross_pin_3_traceqdcArray));
        PARQUET_THROW_NOT_OK(cross_pin_3_time->Finish(&cross_pin_3_timeArray));
        PARQUET_THROW_NOT_OK(db3_scint_L->Finish(&db3_scint_LArray));
        PARQUET_THROW_NOT_OK(db3_scint_R->Finish(&db3_scint_RArray));
        PARQUET_THROW_NOT_OK(db3_ppac_upstream->Finish(&db3_ppac_upstreamArray));
        PARQUET_THROW_NOT_OK(db3_ppac_upstream_left->Finish(&db3_ppac_upstream_leftArray));
        PARQUET_THROW_NOT_OK(db3_ppac_upstream_right->Finish(&db3_ppac_upstream_rightArray));
        PARQUET_THROW_NOT_OK(db3_ppac_upstream_up->Finish(&db3_ppac_upstream_upArray));
        PARQUET_THROW_NOT_OK(db3_ppac_upstream_down->Finish(&db3_ppac_upstream_downArray));
        PARQUET_THROW_NOT_OK(db3_ppac_upstream_LR->Finish(&db3_ppac_upstream_LRArray));
        PARQUET_THROW_NOT_OK(db3_ppac_upstream_UD->Finish(&db3_ppac_upstream_UDArray));
        PARQUET_THROW_NOT_OK(db3_ppac_downstream->Finish(&db3_ppac_downstreamArray));
        PARQUET_THROW_NOT_OK(db3_ppac_downstream_left->Finish(&db3_ppac_downstream_leftArray));
        PARQUET_THROW_NOT_OK(db3_ppac_downstream_right->Finish(&db3_ppac_downstream_rightArray));
        PARQUET_THROW_NOT_OK(db3_ppac_downstream_up->Finish(&db3_ppac_downstream_upArray));
        PARQUET_THROW_NOT_OK(db3_ppac_downstream_down->Finish(&db3_ppac_downstream_downArray));
        PARQUET_THROW_NOT_OK(db3_ppac_downstream_LR->Finish(&db3_ppac_downstream_LRArray));
        PARQUET_THROW_NOT_OK(db3_ppac_downstream_UD->Finish(&db3_ppac_downstream_UDArray));
        PARQUET_THROW_NOT_OK(db4_ppac_left->Finish(&db4_ppac_leftArray));
        PARQUET_THROW_NOT_OK(db4_ppac_right->Finish(&db4_ppac_rightArray));
        PARQUET_THROW_NOT_OK(db4_ppac_up->Finish(&db4_ppac_upArray));
        PARQUET_THROW_NOT_OK(db4_ppac_down->Finish(&db4_ppac_downArray));
        PARQUET_THROW_NOT_OK(db4_ppac_LR->Finish(&db4_ppac_LRArray));
        PARQUET_THROW_NOT_OK(db4_ppac_UD->Finish(&db4_ppac_UDArray));
        PARQUET_THROW_NOT_OK(db5_ppac_upstream->Finish(&db5_ppac_upstreamArray));
        PARQUET_THROW_NOT_OK(db5_ppac_upstream_left->Finish(&db5_ppac_upstream_leftArray));
        PARQUET_THROW_NOT_OK(db5_ppac_upstream_right->Finish(&db5_ppac_upstream_rightArray));
        PARQUET_THROW_NOT_OK(db5_ppac_upstream_up->Finish(&db5_ppac_upstream_upArray));
        PARQUET_THROW_NOT_OK(db5_ppac_upstream_down->Finish(&db5_ppac_upstream_downArray));
        PARQUET_THROW_NOT_OK(db5_ppac_upstream_LR->Finish(&db5_ppac_upstream_LRArray));
        PARQUET_THROW_NOT_OK(db5_ppac_upstream_UD->Finish(&db5_ppac_upstream_UDArray));
        PARQUET_THROW_NOT_OK(db5_ppac_downstream->Finish(&db5_ppac_downstreamArray));
        PARQUET_THROW_NOT_OK(db5_ppac_downstream_left->Finish(&db5_ppac_downstream_leftArray));
        PARQUET_THROW_NOT_OK(db5_ppac_downstream_right->Finish(&db5_ppac_downstream_rightArray));
        PARQUET_THROW_NOT_OK(db5_ppac_downstream_up->Finish(&db5_ppac_downstream_upArray));
        PARQUET_THROW_NOT_OK(db5_ppac_downstream_down->Finish(&db5_ppac_downstream_downArray));
        PARQUET_THROW_NOT_OK(db5_ppac_downstream_LR->Finish(&db5_ppac_downstream_LRArray));
        PARQUET_THROW_NOT_OK(db5_ppac_downstream_UD->Finish(&db5_ppac_downstream_UDArray));
        PARQUET_THROW_NOT_OK(tof0->Finish(&tof0Array));
        PARQUET_THROW_NOT_OK(tof1->Finish(&tof1Array));
        PARQUET_THROW_NOT_OK(tof2->Finish(&tof2Array));
        PARQUET_THROW_NOT_OK(tof3->Finish(&tof3Array));
        PARQUET_THROW_NOT_OK(tof4->Finish(&tof4Array));
        PARQUET_THROW_NOT_OK(tof5->Finish(&tof5Array));
        PARQUET_THROW_NOT_OK(fit_energy->Finish(&fit_energyArray));
        PARQUET_THROW_NOT_OK(yso_energy->Finish(&yso_energyArray));
        PARQUET_THROW_NOT_OK(rit_energy->Finish(&rit_energyArray));

        avec.emplace_back(cross_scint_b1_energyArray);
        avec.emplace_back(cross_scint_b1_timeArray);
        avec.emplace_back(cross_scint_t1_energyArray);
        avec.emplace_back(cross_scint_t1_timeArray);
        avec.emplace_back(cross_scint_v1_energyArray);
        avec.emplace_back(cross_scint_v1_timeArray);
        avec.emplace_back(cross_scint_v1_qdcArray);
        avec.emplace_back(cross_scint_v2_energyArray);
        avec.emplace_back(cross_scint_v2_timeArray);
        avec.emplace_back(cross_scint_v2_qdcArray);
        avec.emplace_back(cross_scint_v3_energyArray);
        avec.emplace_back(cross_scint_v3_timeArray);
        avec.emplace_back(cross_scint_v3_qdcArray);
        avec.emplace_back(cross_scint_v4_energyArray);
        avec.emplace_back(cross_scint_v4_timeArray);
        avec.emplace_back(cross_scint_v4_qdcArray);
        avec.emplace_back(cross_pin_0_energyArray);
        avec.emplace_back(cross_pin_0_tracemaxArray);
        avec.emplace_back(cross_pin_0_traceqdcArray);
        avec.emplace_back(cross_pin_0_timeArray);
        avec.emplace_back(cross_pin_1_energyArray);
        avec.emplace_back(cross_pin_1_tracemaxArray);
        avec.emplace_back(cross_pin_1_traceqdcArray);
        avec.emplace_back(cross_pin_1_timeArray);
        avec.emplace_back(cross_pin_2_energyArray);
        avec.emplace_back(cross_pin_2_tracemaxArray);
        avec.emplace_back(cross_pin_2_traceqdcArray);
        avec.emplace_back(cross_pin_2_timeArray);
        avec.emplace_back(cross_pin_3_energyArray);
        avec.emplace_back(cross_pin_3_tracemaxArray);
        avec.emplace_back(cross_pin_3_traceqdcArray);
        avec.emplace_back(cross_pin_3_timeArray);
        avec.emplace_back(db3_scint_LArray);
        avec.emplace_back(db3_scint_RArray);
        avec.emplace_back(db3_ppac_upstreamArray);
        avec.emplace_back(db3_ppac_upstream_leftArray);
        avec.emplace_back(db3_ppac_upstream_rightArray);
        avec.emplace_back(db3_ppac_upstream_upArray);
        avec.emplace_back(db3_ppac_upstream_downArray);
        avec.emplace_back(db3_ppac_upstream_LRArray);
        avec.emplace_back(db3_ppac_upstream_UDArray);
        avec.emplace_back(db3_ppac_downstreamArray);
        avec.emplace_back(db3_ppac_downstream_leftArray);
        avec.emplace_back(db3_ppac_downstream_rightArray);
        avec.emplace_back(db3_ppac_downstream_upArray);
        avec.emplace_back(db3_ppac_downstream_downArray);
        avec.emplace_back(db3_ppac_downstream_LRArray);
        avec.emplace_back(db3_ppac_downstream_UDArray);
        avec.emplace_back(db4_ppac_leftArray);
        avec.emplace_back(db4_ppac_rightArray);
        avec.emplace_back(db4_ppac_upArray);
        avec.emplace_back(db4_ppac_downArray);
        avec.emplace_back(db4_ppac_LRArray);
        avec.emplace_back(db4_ppac_UDArray);
        avec.emplace_back(db5_ppac_upstreamArray);
        avec.emplace_back(db5_ppac_upstream_leftArray);
        avec.emplace_back(db5_ppac_upstream_rightArray);
        avec.emplace_back(db5_ppac_upstream_upArray);
        avec.emplace_back(db5_ppac_upstream_downArray);
        avec.emplace_back(db5_ppac_upstream_LRArray);
        avec.emplace_back(db5_ppac_upstream_UDArray);
        avec.emplace_back(db5_ppac_downstreamArray);
        avec.emplace_back(db5_ppac_downstream_leftArray);
        avec.emplace_back(db5_ppac_downstream_rightArray);
        avec.emplace_back(db5_ppac_downstream_upArray);
        avec.emplace_back(db5_ppac_downstream_downArray);
        avec.emplace_back(db5_ppac_downstream_LRArray);
        avec.emplace_back(db5_ppac_downstream_UDArray);
        avec.emplace_back(tof0Array);
        avec.emplace_back(tof1Array);
        avec.emplace_back(tof2Array);
        avec.emplace_back(tof3Array);
        avec.emplace_back(tof4Array);
        avec.emplace_back(tof5Array);
        avec.emplace_back(fit_energyArray);
        avec.emplace_back(yso_energyArray);
        avec.emplace_back(rit_energyArray);

        fvec.emplace_back(arrow::field("pid_cross_scint_b1_energy", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_scint_b1_time", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_scint_t1_energy", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_scint_t1_time", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_scint_v1_energy", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_scint_v1_time", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_scint_v1_qdc", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_scint_v2_energy", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_scint_v2_time", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_scint_v2_qdc", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_scint_v3_energy", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_scint_v3_time", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_scint_v3_qdc", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_scint_v4_energy", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_scint_v4_time", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_scint_v4_qdc", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_pin_0_energy", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_pin_0_tracemax", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_pin_0_traceqdc", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_pin_0_time", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_pin_1_energy", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_pin_1_tracemax", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_pin_1_traceqdc", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_pin_1_time", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_pin_2_energy", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_pin_2_tracemax", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_pin_2_traceqdc", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_pin_2_time", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_pin_3_energy", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_pin_3_tracemax", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_pin_3_traceqdc", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_cross_pin_3_time", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db3_scint_L", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db3_scint_R", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db3_ppac_upstream", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db3_ppac_upstream_left", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db3_ppac_upstream_right", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db3_ppac_upstream_up", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db3_ppac_upstream_down", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db3_ppac_upstream_LR", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db3_ppac_upstream_UD", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db3_ppac_downstream", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db3_ppac_downstream_left", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db3_ppac_downstream_right", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db3_ppac_downstream_up", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db3_ppac_downstream_down", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db3_ppac_downstream_LR", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db3_ppac_downstream_UD", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db4_ppac_left", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db4_ppac_right", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db4_ppac_up", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db4_ppac_down", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db4_ppac_LR", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db4_ppac_UD", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db5_ppac_upstream", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db5_ppac_upstream_left", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db5_ppac_upstream_right", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db5_ppac_upstream_up", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db5_ppac_upstream_down", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db5_ppac_upstream_LR", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db5_ppac_upstream_UD", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db5_ppac_downstream", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db5_ppac_downstream_left", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db5_ppac_downstream_right", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db5_ppac_downstream_up", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db5_ppac_downstream_down", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db5_ppac_downstream_LR", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_db5_ppac_downstream_UD", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_tof0", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_tof1", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_tof2", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_tof3", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_tof4", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_tof5", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_fit_energy", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_yso_energy", arrow::float64()));
        fvec.emplace_back(arrow::field("pid_rit_energy", arrow::float64()));
    }

protected:
    std::shared_ptr<arrow::DoubleBuilder> cross_scint_b1_energy;
    std::shared_ptr<arrow::DoubleBuilder> cross_scint_b1_time;
    std::shared_ptr<arrow::DoubleBuilder> cross_scint_t1_energy;
    std::shared_ptr<arrow::DoubleBuilder> cross_scint_t1_time;
    std::shared_ptr<arrow::DoubleBuilder> cross_scint_v1_energy;
    std::shared_ptr<arrow::DoubleBuilder> cross_scint_v1_time;
    std::shared_ptr<arrow::DoubleBuilder> cross_scint_v1_qdc;
    std::shared_ptr<arrow::DoubleBuilder> cross_scint_v2_energy;
    std::shared_ptr<arrow::DoubleBuilder> cross_scint_v2_time;
    std::shared_ptr<arrow::DoubleBuilder> cross_scint_v2_qdc;
    std::shared_ptr<arrow::DoubleBuilder> cross_scint_v3_energy;
    std::shared_ptr<arrow::DoubleBuilder> cross_scint_v3_time;
    std::shared_ptr<arrow::DoubleBuilder> cross_scint_v3_qdc;
    std::shared_ptr<arrow::DoubleBuilder> cross_scint_v4_energy;
    std::shared_ptr<arrow::DoubleBuilder> cross_scint_v4_time;
    std::shared_ptr<arrow::DoubleBuilder> cross_scint_v4_qdc;
    std::shared_ptr<arrow::DoubleBuilder> cross_pin_0_energy;
    std::shared_ptr<arrow::DoubleBuilder> cross_pin_0_tracemax;
    std::shared_ptr<arrow::DoubleBuilder> cross_pin_0_traceqdc;
    std::shared_ptr<arrow::DoubleBuilder> cross_pin_0_time;
    std::shared_ptr<arrow::DoubleBuilder> cross_pin_1_energy;
    std::shared_ptr<arrow::DoubleBuilder> cross_pin_1_tracemax;
    std::shared_ptr<arrow::DoubleBuilder> cross_pin_1_traceqdc;
    std::shared_ptr<arrow::DoubleBuilder> cross_pin_1_time;
    std::shared_ptr<arrow::DoubleBuilder> cross_pin_2_energy;
    std::shared_ptr<arrow::DoubleBuilder> cross_pin_2_tracemax;
    std::shared_ptr<arrow::DoubleBuilder> cross_pin_2_traceqdc;
    std::shared_ptr<arrow::DoubleBuilder> cross_pin_2_time;
    std::shared_ptr<arrow::DoubleBuilder> cross_pin_3_energy;
    std::shared_ptr<arrow::DoubleBuilder> cross_pin_3_tracemax;
    std::shared_ptr<arrow::DoubleBuilder> cross_pin_3_traceqdc;
    std::shared_ptr<arrow::DoubleBuilder> cross_pin_3_time;
    std::shared_ptr<arrow::DoubleBuilder> db3_scint_L;
    std::shared_ptr<arrow::DoubleBuilder> db3_scint_R;
    std::shared_ptr<arrow::DoubleBuilder> db3_ppac_upstream;
    std::shared_ptr<arrow::DoubleBuilder> db3_ppac_upstream_left;
    std::shared_ptr<arrow::DoubleBuilder> db3_ppac_upstream_right;
    std::shared_ptr<arrow::DoubleBuilder> db3_ppac_upstream_up;
    std::shared_ptr<arrow::DoubleBuilder> db3_ppac_upstream_down;
    std::shared_ptr<arrow::DoubleBuilder> db3_ppac_upstream_LR;
    std::shared_ptr<arrow::DoubleBuilder> db3_ppac_upstream_UD;
    std::shared_ptr<arrow::DoubleBuilder> db3_ppac_downstream;
    std::shared_ptr<arrow::DoubleBuilder> db3_ppac_downstream_left;
    std::shared_ptr<arrow::DoubleBuilder> db3_ppac_downstream_right;
    std::shared_ptr<arrow::DoubleBuilder> db3_ppac_downstream_up;
    std::shared_ptr<arrow::DoubleBuilder> db3_ppac_downstream_down;
    std::shared_ptr<arrow::DoubleBuilder> db3_ppac_downstream_LR;
    std::shared_ptr<arrow::DoubleBuilder> db3_ppac_downstream_UD;
    std::shared_ptr<arrow::DoubleBuilder> db4_ppac_left;
    std::shared_ptr<arrow::DoubleBuilder> db4_ppac_right;
    std::shared_ptr<arrow::DoubleBuilder> db4_ppac_up;
    std::shared_ptr<arrow::DoubleBuilder> db4_ppac_down;
    std::shared_ptr<arrow::DoubleBuilder> db4_ppac_LR;
    std::shared_ptr<arrow::DoubleBuilder> db4_ppac_UD;
    std::shared_ptr<arrow::DoubleBuilder> db5_ppac_upstream;
    std::shared_ptr<arrow::DoubleBuilder> db5_ppac_upstream_left;
    std::shared_ptr<arrow::DoubleBuilder> db5_ppac_upstream_right;
    std::shared_ptr<arrow::DoubleBuilder> db5_ppac_upstream_up;
    std::shared_ptr<arrow::DoubleBuilder> db5_ppac_upstream_down;
    std::shared_ptr<arrow::DoubleBuilder> db5_ppac_upstream_LR;
    std::shared_ptr<arrow::DoubleBuilder> db5_ppac_upstream_UD;
    std::shared_ptr<arrow::DoubleBuilder> db5_ppac_downstream;
    std::shared_ptr<arrow::DoubleBuilder> db5_ppac_downstream_left;
    std::shared_ptr<arrow::DoubleBuilder> db5_ppac_downstream_right;
    std::shared_ptr<arrow::DoubleBuilder> db5_ppac_downstream_up;
    std::shared_ptr<arrow::DoubleBuilder> db5_ppac_downstream_down;
    std::shared_ptr<arrow::DoubleBuilder> db5_ppac_downstream_LR;
    std::shared_ptr<arrow::DoubleBuilder> db5_ppac_downstream_UD;

    std::shared_ptr<arrow::DoubleBuilder> tof0;
    std::shared_ptr<arrow::DoubleBuilder> tof1;
    std::shared_ptr<arrow::DoubleBuilder> tof2;
    std::shared_ptr<arrow::DoubleBuilder> tof3;
    std::shared_ptr<arrow::DoubleBuilder> tof4;
    std::shared_ptr<arrow::DoubleBuilder> tof5;
    std::shared_ptr<arrow::DoubleBuilder> fit_energy;
    std::shared_ptr<arrow::DoubleBuilder> yso_energy;
    std::shared_ptr<arrow::DoubleBuilder> rit_energy;
};
#endif // __PID_DATA_BUILDER_HPP__
